# Generated by Django 4.2.5 on 2023-10-14 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0003_customuser_alter_controlvote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='candidates'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_vote',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='controlvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
