# Generated by Django 4.2.5 on 2023-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_candidate_image_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
